name: Maven Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifacts to workflow
      uses: actions/upload-artifact@v2.3.1
      with:
        name: outputjar
        path: target/notsoessentials-INDEV.jar
    - name: Grab artifact
      uses: actions/download-artifact@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: outputjar
        path: build/NotSoEssentials.jar
    - name: Github Releases
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_PATH: build/NotSoEssentials.jar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

